// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHbfutSg7w53yTYOI4Q6FTLlNpFfsxH4',
    appId: '1:560422308373:web:c789fb3069ed03405f5c1c',
    messagingSenderId: '560422308373',
    projectId: 'coffee-app-95562',
    authDomain: 'coffee-app-95562.firebaseapp.com',
    storageBucket: 'coffee-app-95562.appspot.com',
    measurementId: 'G-5G91HLGL4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5gL53X1WPKHSkM3aPLWaxNbGFrQ32A8k',
    appId: '1:560422308373:android:12286bebc6fced755f5c1c',
    messagingSenderId: '560422308373',
    projectId: 'coffee-app-95562',
    storageBucket: 'coffee-app-95562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBBFWKJDVtcNEZOzwFxG3zb5Q5VTY7UM4',
    appId: '1:560422308373:ios:f5ff3318d789cc7a5f5c1c',
    messagingSenderId: '560422308373',
    projectId: 'coffee-app-95562',
    storageBucket: 'coffee-app-95562.appspot.com',
    iosBundleId: 'com.example.coffeeApp',
  );
}
